// RF-072 — Lucide via npm com tree-shaking
// Helper centralizado: importa apenas os ícones usados no app (~40).
// Usar sempre via initIcons() — não chamar lucide.createIcons() diretamente.

import {
  createIcons,
  BarChart2,
  BarChart3,
  Building2,
  Calendar,
  Camera,
  CheckCircle,
  ChevronDown,
  ClipboardList,
  Coins,
  Copy,
  CreditCard,
  Database,
  Download,
  File,
  Flame,
  FolderOpen,
  Home,
  Inbox,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutList,
  Link,
  Menu,
  RefreshCw,
  ScanLine,
  Search,
  Settings,
  Smile,
  Sparkles,
  Tag,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  User,
  Users,
  UsersRound,
  Wallet,
} from 'lucide';

const ICONS = {
  BarChart2,
  BarChart3,
  Building2,
  Calendar,
  Camera,
  CheckCircle,
  ChevronDown,
  ClipboardList,
  Coins,
  Copy,
  CreditCard,
  Database,
  Download,
  File,
  Flame,
  FolderOpen,
  Home,
  Inbox,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutList,
  Link,
  Menu,
  RefreshCw,
  ScanLine,
  Search,
  Settings,
  Smile,
  Sparkles,
  Tag,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  User,
  Users,
  UsersRound,
  Wallet,
};

/**
 * Substitui todos os <i data-lucide="nome"> do DOM pelo SVG correspondente.
 * Deve ser chamada após o DOM estar pronto (módulos ES são sempre diferidos).
 */
export function initIcons() {
  createIcons({ icons: ICONS });
}
